version: '3.3'
services:
    coles-bay-campsites-app:
        restart: always
        image: ghcr.io/maxfire2008/coles-bay-campsites-app:latest
        build:
            context: .
            dockerfile: Dockerfile
        # environment from .env file
        env_file:
            - .env
        volumes:
          - staticfiles:/staticfiles
    nginx:
        ports:
            - 5000:80
        restart: always
        image: nginx:latest
        volumes:
            - staticfiles:/staticfiles
            - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
            - NGINX_HOST=camp.maxstuff.net localhost

volumes:
    staticfiles:
